### ISSUE TITLE
CSS custom properties

### ISSUE THREAD

**Issue by angelsalazar** [forcedotcom/lwc-dev-server-feedback#40]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to inject CSS custom properties to mimic design tokens

**Describe alternatives you've considered**
I have tried to update the .localdevserver/public/assets/styles/styles.css file like
```css
@font-face {
    font-family: 'Neutraface Display';
    src: url('/assets/fonts/NeutrafaceDisplay.woff2') format('woff2'),
         url('/assets/fonts/NeutrafaceDisplay.woff')  format('woff');
    font-weight: 700;
    font-display: swap;
}

:root {
 --lwc-brandAccessibleActive: #005fb2;
}
```

but when running `sfdx force:lightning:lwc:start`, the changes I have done are rollbacked

**Additional context**
none
